import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('focus fills the content viewport and precise time pauses, resumes and respects motion settings', async ({ page }, info) => {
  if (info.project.name === 'desktop') await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/');
  await page.getByLabel('Subject', { exact: true }).selectOption('Maths');
  await page.getByRole('button', { name: 'Continue to Work' }).click();
  await page.getByLabel('One topic', { exact: true }).fill('Algebra');
  await page.getByLabel('One small task').fill('Solve one equation');
  await page.getByRole('button', { name: 'Save task & start' }).click();
  await page.locator('.focus-bg img').evaluate(async (img: HTMLImageElement) => img.decode());
  const bounds = await page.evaluate(() => {
    const box = (s: string) => document.querySelector(s)!.getBoundingClientRect().toJSON();
    return { bg: box('.focus-bg'), body: box('.shell__body'), header: box('.topbar'), width: innerWidth, height: innerHeight };
  });
  expect(bounds.bg.x).toBe(bounds.body.x);
  expect(bounds.bg.right).toBe(bounds.width);
  expect(bounds.bg.y).toBe(bounds.header.bottom);
  expect(bounds.bg.bottom).toBeGreaterThanOrEqual(bounds.height);
  const digits = page.locator('.timer-readout__digits');
  await expect(digits).toHaveText(/\d+:\d{2}\.\d{3}/);
  const initial = await digits.innerText();
  await expect.poll(() => digits.innerText()).not.toBe(initial);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  const paused = await digits.innerText();
  await page.waitForTimeout(200);
  await expect(digits).toHaveText(paused);
  await page.reload();
  await expect(digits).toHaveText(paused);
  await page.getByRole('button', { name: 'Resume', exact: true }).click();
  await expect.poll(() => digits.innerText()).not.toBe(paused);
  await page.screenshot({ path: `artifacts/focus-refined-${info.project.name}.png`, fullPage: true });
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(page.locator('.timer-readout__fraction')).toHaveCount(0);
  await expect(digits).toHaveText(/\d+:\d{2}$/);
  await page.goto('/#/settings');
  await page.getByRole('radio', { name: /^Minutes only/ }).check();
  await page.goto('/#/focus');
  await expect(digits).toHaveCount(0);
  await page.goto('/#/settings');
  await page.getByRole('radio', { name: /^Countdown/ }).check();
  await page.goto('/#/focus');
  await expect(page.locator('.timer-readout__unit')).toHaveText('left');
  await page.setViewportSize({ width: 320, height: 812 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Finish', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Session ended' })).toBeVisible();
});
